repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.12.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^.venv
