---

- name: Prerequisities
  ansible.builtin.include_tasks:
    file: prerequisities.yml
  tags:
    - prerequisities
    - unifi

- name: Add Mongo repo on Bullseye
  ansible.builtin.include_tasks:
    file: mongodb.yml
  when: ansible_distribution_release == "bullseye"
  tags:
    - mongo
    - unifi

- name: Install Unifi
  ansible.builtin.include_tasks:
    file: unifi.yml
  tags:
    - unifi
