---
name: lint with pre-commit on PR

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Lint
        uses: pre-commit/action@v2.0.3
